name: "Regular Checkings of Every Pushes"

on: [push]


jobs:
  install:
    name: "Install Requied Packages"
    container:
      image: node:10
      env:
        NODE_ENV: development
      # options:
    # runs-on: ubuntu-18.04
    steps:
      - name: "List all files"
        run: ls -al
      - name: Check env
        # uses: docker://node:8
        with:
          entrypoint: /bin/sh
        # env:
        #   NODE_ENV: "production"
        run: yarn
  # lint:
  #   name: "Lint Typescripts"
  #   needs: [install]
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - yarn lint
  # build:
  #   name: "Transpile to JavaScript"
  #   needs: [install]
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - yarn build
  # test:
  #   name: "Run Unit Tests"
  #   needs: [install]
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - yarn test
